

---

- name: install apache2
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: install apache2 package
      package:
           name: apache2
           state: present
           update_cache: true
    - name: start apache service
      service:
           name: apache2
           state: started
           enabled: true
 
